### ISSUE TITLE
コミットメッセージのチェックをKFCじゃなくてミスタードーナツにする

### ISSUE THREAD

**Issue by folosuru** [mistems/sandbox#4]
# 理由
ミスタードーナツもおいしいから

## なぜミスタードーナツか
同じ空腹度で換算した時にミスタードーナツの方が個数をいっぱい食べれるから。

## そのほか
いくつかの店では食べ放題（要予約）をやっています

**Comment by shusann01116** [comment]
#1 によると本来このPRはマージされるべきではなかったため、同じ揚げ物のミスタードーナツを導入することにも私は消極的です。

**Comment by hanocha** [comment]
FYI: 白いポンデリングがおいしいらしいです

**Comment by t1nyb0x** [comment]
KFCやミスタードーナッツと同じ揚げ物であるならば、揚げ物でチェックするのはいかがでしょうか・・・？

**Comment by ksmxxxxxx** [comment]
ダンキンドーナツやクリスピー・クリーム・ドーナツなどの候補もあったと思うのですが、検討はされたのでしょうか？

**Comment by folosuru** [comment]
該当Actionが差し戻しされたのでclose
